name: Build cross-platform app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow

    - name: Build executable with PyInstaller
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pyinstaller --onefile --windowed --add-data "hourglass.gif;." main.py
        elif [[ "$RUNNER_OS" == "macOS" || "$RUNNER_OS" == "Linux" ]]; then
          pyinstaller --onefile --windowed --add-data "hourglass.gif:." main.py
        fi
      shell: bash

    - name: Rename output binary
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mv dist/main.exe dist/bookbinding-imposition-windows.exe
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          mv dist/main dist/bookbinding-imposition-macos
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          mv dist/main dist/bookbinding-imposition-linux
        fi
      shell: bash



    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ runner.os }}
        path: dist/bookbinding-imposition-*